### ISSUE TITLE
MangaUpdatesBot

### ISSUE THREAD

**Issue by Talha173** [ohashizu/mangaupdates-bot#8]
I think there should be commands regarding which scans group you specifically want to track so when one chapter of anything drops,you're not looking at 5 same bot messages of the exact same chapter but different scans groups.

Also,if possible give the original scans groups website link.

**Comment by Talha173** [comment]
> > Good suggestions! I believe that first idea could be done pretty easily. However, I don't believe MangaUpdates has every group's websites listed or some groups only have a discord and not a website. I'll see what I can do though.
> 
> If it's possible,our server would like to become a tester for the bot where you can test the development and new features. Also for the website issue,well the above lines,the same reply.

What do you think of this?

**Comment by Talha173** [comment]
> > > > Good suggestions! I believe that first idea could be done pretty easily. However, I don't believe MangaUpdates has every group's websites listed or some groups only have a discord and not a website. I'll see what I can do though.
> > > 
> > > 
> > > If it's possible,our server would like to become a tester for the bot where you can test the development and new features. Also for the website issue,well the above lines,the same reply.
> > 
> > 
> > What do you think of this?
> 
> Well, I have my own private server to test my bot out, so probably not :/

Ah OK 👍

**Comment by Talha173** [comment]
> Hey! I just wanted to update you that I added your feature of selecting the specific scan group. I just need to add the command in the help command. :)

Oh nice,it'll be really handy.Let me know when you add it in the help command too.

**Comment by ohashizu** [comment]
Closed due to inactivity.
