### ISSUE TITLE
More manga websites?

### ISSUE THREAD

**Issue by Sinlukyl** [ohashizu/mangaupdates-bot#9]
I think it would be cool if we could add and keep track with other mangas website like dynasty reader

**Comment by ohashizu** [comment]
I believe that mangaupdates.com takes in all latest chapters released from almost all scan groups, including dynasty-scans's various scan groups. I'm planning on adding a feature that allows you to choose which scan group for each manga chapter update very soon.

**Comment by ohashizu** [comment]
Closing since no response.
